apiVersion: v1
kind: ConfigMap
metadata:
   name: order-service-db-config
   namespace: order-service
data:
   ORDER_SERVICE_DB_NAME: "order_service"
   ORDER_SERVICE_DB_HOST: "postgres-service.default.svc.cluster.local"
   ORDER_SERVICE_DB_PORT: "5432"
