apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  namespace: order-service
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
        - name: order-service
          image: bogdansolga/order-service:0.0.1-2025-07-22-53efb20
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: order-service-db-config
            - secretRef:
                name: order-service-db-secret
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://$(ORDER_SERVICE_DB_HOST):$(ORDER_SERVICE_DB_PORT)/$(ORDER_SERVICE_DB_NAME)
            - name: SPRING_DATASOURCE_USERNAME
              value: $(ORDER_SERVICE_DB_USER)
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: order-service-db-secret
                  key: ORDER_SERVICE_DB_PASSWORD
          resources:
            requests:
              cpu: 750m
              memory: 512M
            limits:
              cpu: 750m
              memory: 512M
